apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "Policy to allow ingress HTTP to frontend"
metadata:
  name: "allow-ingress"
spec:
  endpointSelector:
    matchLabels:
      app: frontend
  ingress:
    - toServices:
        - {}
    -toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "53"
              protocol: UDP