apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow"
spec:
  endpointSelector:
    matchLabels:
      org: alliance
  egress:
  - toServices:
    - k8sService:
        serviceName: deathstar
        namespace: default
