apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "denyall"
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: tiefighter
  role: restricted
  egress:
  - {}
